set(LLVM_ENABLE_PROJECTS "clang;lld;compiler-rt;libcxx;libcxxabi;libunwind" CACHE STRING "")

set(LLVM_TARGETS_TO_BUILD X86 CACHE STRING "")

set(LLVM_BUILD_TOOLS OFF CACHE BOOL "")
set(LLVM_INCLUDE_EXAMPLES OFF CACHE BOOL "")
set(LLVM_INCLUDE_TESTS OFF CACHE BOOL "")
set(LLVM_INCLUDE_BENCHMARKS OFF CACHE BOOL "")

set(LLVM_INSTALL_BINUTILS_SYMLINKS ON CACHE BOOL "")
set(LLVM_INSTALL_CCTOOLS_SYMLINKS ON CACHE BOOL "")

# set(LLVM_PARALLEL_COMPILE_JOBS 2 CACHE STRING "")
set(LLVM_PARALLEL_LINK_JOBS 1 CACHE STRING "")

#set(LLVM_ENABLE_LLD ON CACHE BOOL "")
#set(LLVM_ENABLE_LIBC ON CACHE BOOL "")
#set(LLVM_ENABLE_LIBCXX ON CACHE BOOL "")

#set(CLANG_DEFAULT_CXX_STDLIB libc++ CACHE STRING "")
# set(CLANG_DEFAULT_LINKER lld CACHE STRING "")
#set(CLANG_DEFAULT_RTLIB compiler-rt CACHE STRING "")
#set(CLANG_DEFAULT_UNWINDLIB libunwind CACHE STRING "")

#set(COMPILER_RT_USE_BUILTINS_LIBRARY ON CACHE BOOL "")
#set(SANITIZER_CXX_ABI libc++ CACHE STRING "")
#set(SANITIZER_TEST_CXX libc++ CACHE STRING "")
#set(LIBUNWIND_USE_COMPILER_RT ON CACHE BOOL "")
#set(LIBCXX_USE_COMPILER_RT YES CACHE BOOL "")
#set(LIBCXXABI_USE_COMPILER_RT YES CACHE BOOL "")
#set(LIBCXXABI_USE_LLVM_UNWINDER YES CACHE BOOL "")

set(LLVM_BUILD_LLVM_DYLIB ON CACHE BOOL "")
set(LLVM_LINK_LLVM_DYLIB ON CACHE BOOL "")
# set(LLVM_BUILD_LLVM_C_DYLIB ON CACHE BOOL "")
set(CLANG_LINK_CLANG_DYLIB ON CACHE BOOL "")

set(LLVM_INSTALL_TOOLCHAIN_ONLY ON CACHE BOOL "")

set(PACKAGE_VENDOR "Karellen, Inc. (https://karellen.co)" CACHE STRING "")

set(CMAKE_BUILD_TYPE Release CACHE STRING "")
set(CMAKE_C_FLAGS_RELEASE "-O2" CACHE STRING "")
set(CMAKE_CXX_FLAGS_RELEASE "-O2" CACHE STRING "")
set(CMAKE_ASM_FLAGS_RELEASE "-O2" CACHE STRING "")
