name: karellen-llvm
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
jobs:
  build-primary:
    runs-on: self-hosted
    timeout-minutes: 600
    continue-on-error: false
    env:
      TWINE_USERNAME: __token__
      TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0
      - uses: actions/cache/restore@v3
        id: restore-ccache
        with:
          path: ccache
          key: ccache
      - shell: bash
        run: |
          patch -d llvm-project -p1 < patches/*
          ./docker-build.py -m build
      - uses: actions/cache/save@v3
        id: save-ccache
        if: |
          (success() || failure()) && github.ref_name == 'master'
        with:
          path: ccache
          key: ccache
