name: karellen-llvm
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
jobs:
  build-primary:
    runs-on: self-hosted
    timeout-minutes: 600
    continue-on-error: false
    env:
      TWINE_USERNAME: __token__
      TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      SEGMENT_DOWNLOAD_TIMEOUT_MINS: 60
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

#      - name: Restore Cache
#        uses: actions/cache/restore@v3
#        id: restore-ccache
#        with:
#          path: ccache
#          key: primes-${{ runner.os }}-${{ github.run_id }}
#          restore-keys: primes-${{ runner.os }}

      - name: Install Twine
        shell: bash
        run: |
          set -eEux
          set -o pipefail

          echo "$HOME/.local/bin" >> $GITHUB_PATH
          PATH=$HOME/.local/bin:$PATH
          export PATH
          pip install --no-input --user twine
          twine --version

      - name: Build
        shell: bash
        run: |
          set -eEux
          set -o pipefail

          for p in patches/*; do
            patch -d llvm-project -p1 < $p
          done

          NO_CCACHE=1 ./docker-build.py -m build


      - name: Test
        shell: bash
        run: |
          twine check --strict wheels/*.whl
          ls -la wheels/*

          pip install --no-input --user wheels/*
          python3 -c pass
          which clang
          clang --version

#      - name: Update Cache
#        uses: actions/cache/save@v3
#        id: save-ccache
#        if: (success() || failure()) && github.ref_name == 'master'
#        with:
#          key: primes-${{ runner.os }}-${{ github.run_id }}
#          path: ccache

      - name: Upload Releases
        shell: bash
        if: github.ref_name == 'master'
        run: |
          set -eEux
          set -o pipefail
          shopt -s extglob

          twine upload --non-interactive --skip-existing wheels/!(*debug*).whl

          shopt -u extglob

