name: Upload Missing Wheels to PyPI
on:
  workflow_dispatch:
    inputs:
      release_limit:
        description: "Number of recent releases to check"
        required: false
        default: "10"
jobs:
  upload-missing:
    runs-on: self-hosted
    timeout-minutes: 30
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      TWINE_USERNAME: __token__
      TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
      RELEASE_LIMIT: ${{ inputs.release_limit }}
    steps:
      - uses: actions/checkout@v5

      - name: Install Twine
        shell: bash
        run: |
          set -eEux
          set -o pipefail

          echo "$HOME/.local/bin" >> $GITHUB_PATH
          PATH=$HOME/.local/bin:$PATH
          export PATH
          pip install --no-input --user --break-system-packages twine

      - name: Upload Missing Wheels
        shell: bash
        run: |
          set -eEux
          set -o pipefail

          ./upload-missing-wheels.sh
